---
- name: Run New Relic Installer
  shell: NR_INSTALL_SILENT=true newrelic-install install
  notify:
  - Restart PHP-FPM
  - Restart Nginx HTTP server

- name: Restart PHP-FPM
  service: name=php5-fpm state=restarted

- name: Restart Nginx HTTP server
  service: name=nginx state=restarted
